usertrack: Handle expiry cancellation correctly
It isn't enough to delete from the expiry dict.  We have to unschedule
the callback as well, or it will run anyway and delete the user.

This behaviour is wrong and causes exceptions in an easy-to-test
scenario:

--> :foo KICK #channel bar :msg
[ within 30 seconds of KICK, a rejoin: ]
--> :bar JOIN #channel
[ 30 seconds after KICK ]: Deleted user bar
--> :bar PRIVMSG #channel :foo

  File "PyIRC/extensions/usertrack.py", line 567, in message
    if hostmask.username != user.username or hostmask.host != user.host:
AttributeError: 'NoneType' object has no attribute 'username'